#!/bin/bash
#
# forever-node-valet24   Startup script for the Forever nodejs valet24
#
# chkconfig: - 94 03
# description: Run-level Startup script for the forever nodejs valet24
#              
### BEGIN INIT INFO
# Provides: forever-node-valet24
# Required-Start: $local_fs $remote_fs $network
# Required-Stop: $local_fs $remote_fs $network
# Default-Start 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: forever nodejs valet24
### END INIT INFO

# Source function library.
#if [ -f /etc/init.d/functions ] ; then
#  . /etc/init.d/functions
#elif [ -f /etc/rc.d/init.d/functions ] ; then
#  . /etc/rc.d/init.d/functions

#else
  #exit 0
#fi

NODEJS_OWNER=valet24
NODE_PATH=/usr/local/lib/node_modules
FOREVER=/usr/bin/forever
FOREVER_LOG="~/log/forever.log"
FORVER_ERR="~/log/forever.log"
FOREVER_OUT="~/log/forever-output.log"
NODEJS_FILE="~/bin/www"

LOCKFILE=/var/lock/forever-node-valet24
RETVAL=0

if [ ! -f $FOREVER ]
then
    echo "Forever node-valet24 startup: cannot start because $FOREVER not found"
    exit 1
fi

# Forever node-valet24 startup
start() {
        if [ -f $LOCKFILE ]
        then
            echo $"Forever node-valet24 startup: cannot start because lockfile=$LOCKFILE is exist"
        exit 1
        fi
        echo -n $"Starting Forever node-valet24"
        #su - $NODEJS_OWNER -c "cd ~ && export NODE_PATH=${NODE_PATH} && sudo forever -a -l $FOREVER_LOG -e $FOREVER_LOG -o $FOREVER_OUT start $NODEJS_FILE >> $FOREVER_LOG"
        su - $NODEJS_OWNER -c "export NODE_PATH=${NODE_PATH} && $FOREVER -a -l $FOREVER_LOG -e $FOREVER_LOG -o $FOREVER_OUT start $NODEJS_FILE >> $FOREVER_LOG"
        RETVAL=$?
        echo
        if [ $RETVAL -eq 0 ]
        then 
            touch $LOCKFILE
            return $RETVAL
        fi
}

# Forever node-valet24 stopping
stop() {
        if [ ! -f $LOCKFILE ]
        then
            echo $"Forever node-valet24 stopping: cannot stopping because lockfile=$LOCKFILE is not exist"
        exit 1
        fi
        echo -n $"Stopping Forever node-valet24"
        #su - $NODEJS_OWNER -c "cd ~ && sudo forever -a -l $FOREVER_LOG -e $FOREVER_LOG -o FOREVER_OUT stop $NODEJS_FILE >> $FOREVER_LOG"
        su - $NODEJS_OWNER -c "$FOREVER -a -l $FOREVER_LOG -e $FOREVER_LOG -o FOREVER_OUT stop $NODEJS_FILE >> $FOREVER_LOG"
        echo=$?
        RETVAL=$?
        if [ $RETVAL -eq 0 ]
        then
            rm -rf $LOCKFILE
            return $RETVAL
        fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    reload|restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: basename $0 start|stop|restart|reload"
        exit 1
esac

exit 0
